### ISSUE TITLE
Compiling TensorFlow Custom Operation

### ISSUE THREAD

**Issue by BarthaBRW** [githubharald/CTCWordBeamSearch#14]
The implementation looks promising.
Is there a prebuilt _FWordBeamSearch.so_ available for testing?

**Comment by githubharald** [comment]
No, there is no pre-built custom TF operation because of the large number of combinations of TF, OS, ...
See the README on how to build the custom operation.

**Comment by BarthaBRW** [comment]
Ok, I understand. Thank you for your reply. I just could not build following the TF documentation, but I'll give another try.

**Comment by githubharald** [comment]
it should be enough to [run the script buildTF.sh](https://github.com/githubharald/CTCWordBeamSearch#1-compile) from the command line to build the custom op.
Do you encounter any problems? If yes, please fill out the [issue template](https://github.com/githubharald/CTCWordBeamSearch/blob/master/ISSUE_TEMPLATE.md) which asks you for all relevant information.

**Comment by BarthaBRW** [comment]
Running the buildTF.sh script throws this error:
> $ ./buildTF.sh
> Single-threaded decoding
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/brw/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
>     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
>   File "/home/brw/.local/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
>     from tensorflow.python import pywrap_tensorflow
> ImportError: cannot import name 'pywrap_tensorflow'
> Your TF version is 
> TF versions 1.3.0, 1.4.0, 1.5.0 and 1.6.0 are tested
> Compiling for TF 1.5.0 or 1.6.0 now ...
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/brw/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
>     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
>   File "/home/brw/.local/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
>     from tensorflow.python import pywrap_tensorflow
> ImportError: cannot import name 'pywrap_tensorflow'
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/brw/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
>     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
>   File "/home/brw/.local/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
>     from tensorflow.python import pywrap_tensorflow
> ImportError: cannot import name 'pywrap_tensorflow'
> In file included from /usr/include/tensorflow/core/framework/op.h:23:0,
>                  from ../src/TFWordBeamSearch.cpp:1:
> /usr/include/tensorflow/core/framework/op_def_builder.h:24:10: fatal error: tensorflow/core/framework/op_def.pb.h: No such file or directory
>  #include "tensorflow/core/framework/op_def.pb.h"
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.

I copied the tensorflow source folder to the /usr/include/tensorflow, but it indeed does not contain the given .pb.h file. What am I doing wrong?

**Comment by githubharald** [comment]
Closing because of inactivity.

**Comment by sdll** [comment]
I solved the problem of missing headers by compiling with those from python2 tensorflow package.
