### ISSUE TITLE
Building a custom operation fails with pip3 tf

### ISSUE THREAD

**Issue by sdll** [githubharald/CTCWordBeamSearch#15]
If you create a new issue, please provide the following information:

1. Which program causes the problem
* [buildTF](https://github.com/githubharald/CTCWordBeamSearch/blob/master/cpp/proj/buildTF.sh)

2. Versions
* TensorFlow version

```
pip3 freeze | grep tf
tf==1.0.0
```

```
pip2 freeze | grep tensorflow
tensorflow==1.12.0
```

* Python version

Python 2.7.15
Python 3.7.0

* C++ compiler

Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

* Operating system

ProductName:	Mac OS X
ProductVersion:	10.14.1
BuildVersion:	18B75

3. Issue
* Which result/error did you get?
```shell
Single-threaded decoding
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'
Your TF version is
TF versions 1.3.0, 1.4.0, 1.5.0 and 1.6.0 are tested
Compiling for TF 1.5.0 or 1.6.0 now ...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'
../src/TFWordBeamSearch.cpp:1:10: fatal error: 'tensorflow/core/framework/op.h' file not found
#include <tensorflow/core/framework/op.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
* If you think the result is wrong - what result did you expect instead?

Looking at the code, the pip3 `tf` package lacks the headers shipped with the pip2 `tensorflow`. 

I did compile the binary by changing to python2.

**Comment by jagmohan12** [comment]
i am having the same problem..can you tell me how can i correct it
